### ISSUE TITLE
SQL results with odd characters cause Vertx.Exception

### ISSUE THREAD

**Issue by markhumphreysjhc** [timyates/mod-jdbc-persistor#25]
I am querying a database and the result field cause exceptions ...

Caught error with SELECT: Cannot have objects of class class [B in JSON
org.vertx.java.core.VertxException: Cannot have objects of class class [B in JSO
N
        at org.vertx.java.core.json.JsonElement.convertMap(JsonElement.java:60)
        at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:56)
        at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:45)
        at com.bloidonia.vertx.mods.JsonUtils.listOfMapsToJsonArray(JsonUtils.ja
va:61)
        at com.bloidonia.vertx.mods.JdbcProcessor$4.process(JdbcProcessor.java:2
78)

The field that seems to cause the issue contains contents like this ...

"*XXX - YYY/ZZZZ : AAAA/BBBBB"

I can't change the contents of the field as they are an external database.

Are there any suggestions for getting passed this issue ?

Thanks

**Comment by frangarcia** [comment]
For those having these problems, I have also realised that using the concat with some mixed values (string and numbers) in an sql query in old versions of mysql, returns an array of bytes. e.g. concat("hello",1) as str. 

The fix for this would be casting before concatenating concat("hello",cast(1 as char)).
