### ISSUE TITLE
Method Connection.prepareStatement is not yet implemented on Pentaho

### ISSUE THREAD

**Issue by safrinakharisma** [timyates/mod-jdbc-persistor#36]
Hallo I'm connecting pentaho to presto database. I can get data from table input but I can't to sorting the data. When I short the data there is error like this : 

org.pentaho.di.core.exception.KettleStepException: 
Unable to get queryfields for SQL: 
SELECT "common.shop.name" as shop_name,
"common.shop.id" as shop_id,
"common.user.id" as user_id ,
"common.filter.keywords" as keyword,
"iris_date" as iris_date,
COUNT("common.ad.id") as click
FROM "ads"."click_v2_go"
WHERE "common.shop.name" ='Amzn Go'
AND  "common.filter.keywords" like '%pulsa%'
AND "iris_date" >='2017-12-01'
group by 1,2,3,4,5

Couldn't get field info from [SELECT "common.shop.name" as shop_name,
"common.shop.id" as shop_id,
"common.user.id" as user_id ,
"common.filter.keywords" as keyword,
"iris_date" as iris_date,
COUNT("common.ad.id") as click
FROM "ads"."click_v2_go"
WHERE "common.shop.name" ='Amzn Go'
AND  "common.filter.keywords" like '%pulsa%'
AND "iris_date" >='2017-12-01'
group by 1,2,3,4,5]

Method Connection.prepareStatement is not yet implemented

	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:247)
	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2005)
	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1834)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1903)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1868)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1854)
	at org.pentaho.di.ui.trans.steps.sort.SortRowsDialog.get(SortRowsDialog.java:574)
	at org.pentaho.di.ui.trans.steps.sort.SortRowsDialog.access$1200(SortRowsDialog.java:71)
	at org.pentaho.di.ui.trans.steps.sort.SortRowsDialog$7.handleEvent(SortRowsDialog.java:404)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.trans.steps.sort.SortRowsDialog.open(SortRowsDialog.java:458)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:127)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8728)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3214)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:780)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1366)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7984)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9245)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:692)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
Couldn't get field info from [SELECT "common.shop.name" as shop_name,
"common.shop.id" as shop_id,
"common.user.id" as user_id ,
"common.filter.keywords" as keyword,
"iris_date" as iris_date,
COUNT("common.ad.id") as click
FROM "ads"."click_v2_go"
WHERE "common.shop.name" ='Amzn Go'
AND  "common.filter.keywords" like '%pulsa%'
AND "iris_date" >='2017-12-01'
group by 1,2,3,4,5]

Method Connection.prepareStatement is not yet implemented

	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2359)
	at org.pentaho.di.core.database.Database.getQueryFields(Database.java:2198)
	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:236)
	... 33 more
Caused by: com.facebook.presto.jdbc.NotImplementedException: Method Connection.prepareStatement is not yet implemented
	at com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:112)
	at org.pentaho.di.core.database.Database.getQueryFieldsFallback(Database.java:2320)
	... 35 more

Notes : I have done install JDBC package for presto and metadata on pentaho marketplace. 

Anybody can help for solve this problem?

Thanks

**Comment by timyates** [comment]
https://github.com/prestodb/presto/issues/1195

Not sure anything can be done in this module to fix the jdbc driver missing a method we require
